name: talker_shop_app_example
description: Talker flutter example shop application
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  
  get_it: ^8.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  url_launcher: ^6.2.4
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
