name: talker_flutter

on:
  push:
    paths:
      - "packages/talker_flutter/**"
      - "/talker_flutter.yaml"

  pull_request:
    paths:
      - "packages/talker_flutter/**"
      - "/talker_flutter.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/talker_flutter

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "12.x"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings .

      # - name: Run tests
      #   run: flutter test --no-pub --coverage

      # - name: Check Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
      #   with:
      #     path: packages/talker_flutter/coverage/lcov.info
      #     min_coverage: 0

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Build WEB
      #   run: |
      #     cd example
      #     flutter build web --release --web-renderer canvaskit

      # - name: Deploy WEB
      #   run: |
      #     cd example/build/web
      #     git init

      #     git config --global user.email youngfrezyx@gmail.com
      #     git config --global user.name Stanislav Ilin
      #     git status

      #     git remote add origin https://${{secrets.commit_secret}}@github.com/Frezyx/talker.git
      #     git checkout -b gh-pages
      #     git add --all
      #     git commit -m "update"
      #     git push origin gh-pages -f
