name: talker_drift_logger
description: Lightweight and customizable Drift SQL logger on talker base
version: 5.0.0

homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - database
  - drift
  - sqlite
  - logging
  - log

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  talker: ^5.0.0
  drift: ^2.17.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.23.1
  sqlite3: ^2.4.0
