name: example_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: 1.2.0
  talker_dart_frog_logger:
    path:
      ../

dev_dependencies:
  test: ^1.25.15
  very_good_analysis: ^7.0.0
