name: talker

on:
  push:
    paths:
      - "packages/talker/**"
      - ".github/workflows/talker.yaml"
  pull_request:
    paths:
      - "packages/talker/**"
      - ".github/workflows/talker.yaml"
permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      package: talker
      sdk: dart
