name: talker_flutter

on:
  push:
    paths:
      - "packages/talker_flutter/**"
      - ".github/workflows/talker_flutter.yaml"
  pull_request:
    paths:
      - "packages/talker_flutter/**"
      - ".github/workflows/talker_flutter.yaml"
permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      package: talker_flutter
      sdk: flutter
